#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Nov 18, 2024 09:45:49 AM CET  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    system_shutdown_png "./assets/graphic/system-shutdown.png" 
    question_png "./assets/graphic/question.png" 
    information_png "./assets/graphic/information.png" 
    home_png "./assets/graphic/home.png" 
    edit_copy_png "./assets/graphic/edit-copy.png" 
    list_add_png "./assets/graphic/list-add.png" 
    applications_system_png "./assets/graphic/applications-system.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #919191
set vTcl(actual_gui_fg) black
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) notsodark



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 2 -menu $top.m47 -background #919191 -highlightbackground gray82 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 930x607+393+111
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::frame "$top.tFr50" \
        -borderwidth 2 -relief sunken -width 920 -height 52 
    vTcl:DefineAlias "$top.tFr50" "TfrmStatus" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr50
    ttk::label "$site_3_0.tLa47" \
        -font "-family {DejaVu Sans} -size 12 -weight bold" -relief flat \
        -anchor center -justify left -text "Status" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa47" "lblStatus" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa64" \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "Runtime:" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa64" "TLabel9" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa48" \
        -font "-family {DejaVu Sans} -size 14 -weight bold" -relief flat \
        -anchor w -justify left -textvariable "::StatusTime" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa48" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa47 \
        -in $site_3_0 -x 190 -y 5 -width 555 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa64 \
        -in $site_3_0 -x 10 -y 5 -width 63 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa48 \
        -in $site_3_0 -x 80 -y 5 -width 94 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::frame "$top.tFr57" \
        -borderwidth 2 -relief flat -width 125 -height 75 
    vTcl:DefineAlias "$top.tFr57" "TfrmAbout" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr57
    ttk::label "$site_3_0.tLa56" \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor center \
        -justify left -text "on About screen" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa56" "TLabel4_1" vTcl:WidgetProc "Toplevel1" 1
    message "$site_3_0.mes48" \
        -background #919191 -font "-family {DejaVu Sans} -size 10" \
        -foreground black -highlightbackground #919191 -highlightcolor black \
        -padx 1 -pady 1 -text "Program utvikla av Halvard" -width 842 
    vTcl:DefineAlias "$site_3_0.mes48" "Message2" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu52" \
        -command "on_TBtnDismiss" -text "Dismiss" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu52" "TBtnDismiss_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa56 \
        -in $site_3_0 -x 10 -y 20 -width 904 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes48 \
        -in $site_3_0 -x 40 -y 60 -width 842 -relwidth 0 -height 371 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu52 \
        -in $site_3_0 -x 415 -y 420 -width 98 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr57
    frame "$top.fra52" \
        -borderwidth 2 -background #919191 -height 155 \
        -highlightbackground gray82 -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra52" "frmMoveBetweenLists" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    ttk::button "$site_3_0.tBu56" \
        -command "on_TBtnDismiss" -text "Dismiss" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu56" "TBtnDismiss_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$site_3_0.scr50" \
        -background #919191 -height 75 -highlightbackground #919191 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr50" "Scrolledlistbox2" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr50.01 configure -background white \
        -cursor xterm \
        -disabledforeground #6d6d6d \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #919191 \
        -highlightcolor #919191 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$site_3_0.scr48" \
        -background #919191 -height 75 -highlightbackground #919191 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr48" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr48.01 configure -background white \
        -cursor xterm \
        -disabledforeground #6d6d6d \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #919191 \
        -highlightcolor #919191 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10
    ttk::label "$site_3_0.tLa49" \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor center \
        -justify left -text "on Move Between Lists screen" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa49" "TLabel4_2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu56 \
        -in $site_3_0 -x 414 -y 417 -width 98 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr50 \
        -in $site_3_0 -x 503 -y 10 -width 418 -relwidth 0 -height 398 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr48 \
        -in $site_3_0 -x 5 -y 10 -width 418 -relwidth 0 -height 398 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa49 \
        -in $site_3_0 -x 330 -y 10 -width 274 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra52
    frame "$top.fra49" \
        -borderwidth 2 -relief ridge -background #919191 -height 45 \
        -highlightbackground gray82 -highlightcolor black -width 930 
    vTcl:DefineAlias "$top.fra49" "TfrmHeader" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra49
    ttk::button "$site_3_0.tBu49" \
        -command "on_TBtnExit" -text "Exit" -image system_shutdown_png \
        -compound none 
    vTcl:DefineAlias "$site_3_0.tBu49" "TBtnExit" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Shutdown}
    }
    vTcl:copy_lock $site_3_0.tBu49
    ttk::label "$site_3_0.tLa57" \
        -font "-family {DejaVu Sans} -size 10" -relief raised -anchor center \
        -justify left -text "h" -compound none 
    vTcl:DefineAlias "$site_3_0.tLa57" "TLblHamburger" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tLa57 <Button-1> {
        lambda e: on_Hamburger(e)
    }
    vTcl:copy_lock $site_3_0.tLa57
    ttk::frame "$site_3_0.tFr48" \
        -borderwidth 1 -relief flat -width 80 -height 45 
    vTcl:DefineAlias "$site_3_0.tFr48" "TFrame3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tFr48
    ttk::button "$site_4_0.tBu54" \
        -command "on_TBtnHelp" -text "Help" -image question_png \
        -compound none 
    vTcl:DefineAlias "$site_4_0.tBu54" "TBtnHelp" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.tBu54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Help}
    }
    ttk::button "$site_4_0.tBu55" \
        -command "on_TBtnAbout" -text "About" -image information_png \
        -compound none 
    vTcl:DefineAlias "$site_4_0.tBu55" "TBtnAbout" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.tBu55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {About}
    }
    place $site_4_0.tBu54 \
        -in $site_4_0 -x 0 -y 0 -width 38 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tBu55 \
        -in $site_4_0 -x 38 -y 0 -width 38 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    label "$site_3_0.lab67" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #919191 -compound left -disabledforeground #9d9d9d \
        -font "-family {DejaVu Sans} -size 20 -weight bold" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "Articles Lookup" 
    vTcl:DefineAlias "$site_3_0.lab67" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 885 -y 2 -width 38 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa57 \
        -in $site_3_0 -x 1 -y 2 -width 38 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.tFr48 \
        -in $site_3_0 -x 773 -y 0 -width 80 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 160 -y 2 -width 610 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::frame "$top.tFr47" \
        -borderwidth 1 -relief flat -width 155 -height 405 
    vTcl:DefineAlias "$top.tFr47" "TFrameMenu" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr47
    ttk::button "$site_3_0.tBu59" \
        -command "on_TBtnHome" -text "Home           " -image home_png \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tBu59" "TBtnHome" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu59 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Home}
    }
    vTcl:copy_lock $site_3_0.tBu59
    ttk::button "$site_3_0.tBu50" \
        -command "on_TBtnEditCopy" -text "Edit Items   " -image edit_copy_png \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tBu50" "TBtnEditCopy" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Edit or copy items between lists}
    }
    vTcl:copy_lock $site_3_0.tBu50
    ttk::button "$site_3_0.tBu57" \
        -command "on_TBtnListAdd" -text "Add a Issue " -image list_add_png \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tBu57" "TBtnListAdd" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Add new item to list}
    }
    vTcl:copy_lock $site_3_0.tBu57
    ttk::button "$site_3_0.tBu53" \
        -command "on_TBtnPreferences" -text "Preferences" \
        -image applications_system_png -compound left 
    vTcl:DefineAlias "$site_3_0.tBu53" "TBtnPreferences" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set Preferences}
    }
    vTcl:copy_lock $site_3_0.tBu53
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 0 -y 0 -width 150 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu50 \
        -in $site_3_0 -x 0 -y 90 -width 150 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu57 \
        -in $site_3_0 -x 0 -y 45 -width 150 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 0 -y 135 -width 150 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.fra53" \
        -borderwidth 2 -background #919191 -height 155 \
        -highlightbackground gray82 -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra53" "frmStartupSplashScreen" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra53
    ttk::button "$site_3_0.tBu56" \
        -command "on_TBtnStart" -text "Start" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu56" "TBtnStart" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Start this application}
    }
    ttk::label "$site_3_0.tLa50" \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "Tlabel" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa50" "TLblFac_simile" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa51" \
        -font "-family {DejaVu Serif} -size 14" -relief flat -anchor w \
        -justify left -text "Tlabel" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa51" "TLblIntro" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu56 \
        -in $site_3_0 -x 416 -y 513 -width 98 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa50 \
        -in $site_3_0 -x 314 -y 32 -width 597 -relwidth 0 -height 460 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 2 -y 19 -width 295 -relwidth 0 -height 511 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.fra54" \
        -borderwidth 2 -background #919191 -height 155 \
        -highlightbackground gray82 -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra54" "frmHome" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra54
    ttk::label "$site_3_0.tLa61" \
        -font "-family {DejaVu Sans} -size 14" -relief flat -anchor center \
        -justify left -text "Pleas wait ..." -compound left 
    vTcl:DefineAlias "$site_3_0.tLa61" "TLabel10" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa62" \
        -font "-family {DejaVu Sans} -size 14" -relief flat -anchor center \
        -justify left -text "Tlabel" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa62" "TLblAboutWeeklyList" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledwindow::CreateCmd "$site_3_0.scr51" \
        -borderwidth 2 -relief groove -background #919191 -height 100 \
        -highlightbackground #919191 -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_3_0.scr51" "Scrolledwindow1" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr51.01 configure -background white \
        -borderwidth 2 \
        -height 75 \
        -highlightbackground #919191 \
        -highlightcolor black \
        -insertbackground black \
        -relief groove \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 125
    place $site_3_0.tLa61 \
        -in $site_3_0 -x 563 -y 160 -width 154 -relwidth 0 -height 81 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa62 \
        -in $site_3_0 -x 170 -y 0 -width 374 -relwidth 0 -height 454 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr51 \
        -in $site_3_0 -x 574 -y 0 -width 184 -relwidth 0 -height 454 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.fra51" \
        -borderwidth 2 -background #919191 -height 155 \
        -highlightbackground gray82 -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra51" "frmAddIssues" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra51
    ttk::button "$site_3_0.tBu56" \
        -command "on_TBtnDismiss" -text "Dismiss" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu56" "TBtnDismiss_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa53" \
        -font "-family {DejaVu Sans} -size 12" -relief flat -anchor w \
        -justify left -compound left 
    vTcl:DefineAlias "$site_3_0.tLa53" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn48" \
        -font "-family {DejaVu Sans} -size 10" -justify center -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn48" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa55" \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor center \
        -justify left -text "for example:
Oct. 29, 2024" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa55" "TLabel8" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa59" \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor w \
        -justify left -text "1 .. 653" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa59" "TLabel7" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$site_3_0.scr47" \
        -background #919191 -height 75 -highlightbackground #919191 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr47" "ScrolledlistboxUrl" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr47.01 configure -background white \
        -cursor xterm \
        -disabledforeground #6d6d6d \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #919191 \
        -highlightcolor #919191 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10
    ttk::label "$site_3_0.tLa54" \
        -font "-family {DejaVu Sans} -size 12" -relief flat -anchor w \
        -justify left -text "+ actual issue number:   #" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa54" "TLabel6" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn47" \
        -font "-family {DejaVu Sans} -size 10" -justify center -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn47" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa52" \
        -font "-family {DejaVu Sans} -size 12" -relief flat -anchor w \
        -justify left -text "Read url from a pycoders issue:" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa52" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa60" \
        -font "-family {DejaVu Sans} -size 20 -weight bold" -relief flat \
        -anchor center -justify left -text "TLabel " -compound left 
    vTcl:DefineAlias "$site_3_0.tLa60" "TLbl_warning" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu58" \
        -command "on_TBtnGo1" -text "go" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu58" "TBtnGo1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu58 <<SetBalloon>> {
        set ::vTcl::balloon::%W {read the entrybox value and start web scraping}
    }
    place $site_3_0.tBu56 \
        -in $site_3_0 -x 418 -y 420 -width 98 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa53 \
        -in $site_3_0 -x 60 -y 48 -width 251 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn48 \
        -in $site_3_0 -x 609 -y 44 -width 120 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa55 \
        -in $site_3_0 -x 621 -y 2 -width 105 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa59 \
        -in $site_3_0 -x 530 -y 20 -width 64 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr47 \
        -in $site_3_0 -x 28 -y 88 -width 878 -relwidth 0 -height 318 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 311 -y 48 -width 221 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn47 \
        -in $site_3_0 -x 534 -y 44 -width 46 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 30 -y 20 -width 265 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa60 \
        -in $site_3_0 -x 116 -y 157 -width 697 -relwidth 0 -height 193 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu58 \
        -in $site_3_0 -x 760 -y 44 -width 48 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra51
    frame "$top.fra48" \
        -borderwidth 2 -background #919191 -height 155 \
        -highlightbackground gray82 -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra48" "frmArticles" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    frame "$site_3_0.fra50" \
        -background #919191 -height 75 -highlightbackground #919191 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.fra50" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra50
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$site_4_0.scr49" \
        -background #919191 -height 15 -highlightbackground #919191 \
        -highlightcolor black -width 30 
    vTcl:DefineAlias "$site_4_0.scr49" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

        $base.fra48.fra50.scr49.01 configure -columns Col1 -height 4
        $base.fra48.fra50.scr49.01 configure -columns {Col1}
        $base.fra48.fra50.scr49.01 heading #0 -text {chk}
        $base.fra48.fra50.scr49.01 heading #0 -anchor center
        $base.fra48.fra50.scr49.01 column #0 -width 171
        $base.fra48.fra50.scr49.01 column #0 -minwidth 5
        $base.fra48.fra50.scr49.01 column #0 -stretch 1
        $base.fra48.fra50.scr49.01 column #0 -anchor center
        $base.fra48.fra50.scr49.01 heading Col1 -text {Url}
        $base.fra48.fra50.scr49.01 heading Col1 -anchor center
        $base.fra48.fra50.scr49.01 column Col1 -width 733
        $base.fra48.fra50.scr49.01 column Col1 -minwidth 20
        $base.fra48.fra50.scr49.01 column Col1 -stretch 1
        $base.fra48.fra50.scr49.01 column Col1 -anchor w
    ttk::button "$site_4_0.tBu51" \
        -command "on_TBtnBrowser" -text "View selected items in your Browser" \
        -compound left 
    vTcl:DefineAlias "$site_4_0.tBu51" "TBtnBrowser" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_4_0.tBu47" \
        -command "on_TBtnRemoveCheckmarks" -text "Remove Checkmarks" \
        -compound left 
    vTcl:DefineAlias "$site_4_0.tBu47" "TBtnRemoveCheckmarks" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_4_0.tBu60" \
        -command "on_TBtnCheckAll" -text "Check All" -compound left 
    vTcl:DefineAlias "$site_4_0.tBu60" "TBtnCheckAll" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.scr49 \
        -in $site_4_0 -x 3 -y 0 -width 922 -relwidth 0 -height 407 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu51 \
        -in $site_4_0 -x 321 -y 420 -width 280 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu47 \
        -in $site_4_0 -x 121 -y 420 -width 180 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu60 \
        -in $site_4_0 -x 3 -y 420 -height 40 -relheight 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra50 \
        -in $site_3_0 -x 0 -y 0 -width 925 -relwidth 0 -height 470 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.fra47" \
        -borderwidth 2 -background #919191 -height 155 \
        -highlightbackground gray82 -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra47" "frmPreferences" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    ttk::label "$site_3_0.tLa49" \
        -font "-family {DejaVu Sans} -size 10" -relief flat -anchor center \
        -justify left -text "on Preferences screen" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa49" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #919191 -compound left -disabledforeground #9d9d9d \
        -font "-family {DejaVu Sans} -size 10" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Label" 
    vTcl:DefineAlias "$site_3_0.lab48" "LblName" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #919191 -compound left -disabledforeground #9d9d9d \
        -font "-family {DejaVu Sans} -size 10" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Label" 
    vTcl:DefineAlias "$site_3_0.lab49" "LblResolution" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu56" \
        -command "on_TBtnDismiss" -text "Dismiss" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu56" "TBtnDismiss_1_1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #919191 -compound left -disabledforeground #9d9d9d \
        -font "-family {DejaVu Sans} -size 10" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Label" 
    vTcl:DefineAlias "$site_3_0.lab50" "LblPosition" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa49 \
        -in $site_3_0 -x 330 -y 10 -width 274 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 40 -width 229 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 10 -y 70 -width 229 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu56 \
        -in $site_3_0 -x 415 -y 420 -width 98 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 10 -y 110 -width 229 -height 21 -anchor nw \
        -bordermode ignore 
    ttk::frame "$top.tFr58" \
        -borderwidth 2 -relief flat -width 125 -height 75 
    vTcl:DefineAlias "$top.tFr58" "TfrmHelp" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr58
    ttk::button "$site_3_0.tBu48" \
        -command "on_TBtnDismiss" -text "Dismiss" -compound left 
    vTcl:DefineAlias "$site_3_0.tBu48" "TBtnDismiss" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$site_3_0.scr52" \
        -borderwidth 2 -relief groove -background #919191 -height 75 \
        -highlightbackground #919191 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr52" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr52.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #919191 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 412 -y 419 -width 98 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr52 \
        -in $site_3_0 -x 0 -y 0 -width 926 -relwidth 0 -height 411 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr50 \
        -in $top -x 5 -y 520 -width 920 -relwidth 0 -height 52 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr57 \
        -in $top -x 0 -y 49 -width 926 -relwidth 0 -height 470 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 0 -y 49 -width 926 -relwidth 0 -height 470 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 0 -y 0 -width 930 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr47 \
        -in $top -x 0 -y 50 -width 155 -relwidth 0 -height 405 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 0 -y 0 -width 930 -relwidth 0 -height 574 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra54 \
        -in $top -x 0 -y 50 -width 926 -relwidth 0 -height 470 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -y 50 -width 926 -height 470 -anchor nw \
        -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -y 49 -width 930 -relwidth 0 -height 470 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -y 49 -width 926 -relwidth 0 -height 470 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr58 \
        -in $top -x 0 -y 49 -width 926 -relwidth 0 -height 470 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

